const SEARCH_FOCUSED = 'header/SEARCH_FOCUSED',
    SEARCH_BLURS = 'header/SEARCH_BLURS',
    CHANGE_LIST = 'CHANGE_LIST',
    MOUSEENTER = 'MOUSEENTER',
    MOUSELEAVE = 'MOUSELEAVE',
    SWITCH_PAGE = 'SWITCH_PAGE';

export {
    SEARCH_BLURS,
    SEARCH_FOCUSED,
    MOUSEENTER,
    MOUSELEAVE,
    SWITCH_PAGE,
    CHANGE_LIST
}
